spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/jooq_experiment}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org.flyway: info